name: Greet Everyone
# This workflow is triggered on commits to the repository.
on: 
  push:
    branches: [master]
defaults:
  run:
    shell: bash
jobs:
  build:
    # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        # This step runs the script
        - name: Run Script
          run: sh ./generateLog.sh
          id: run_script
        # This step prints an output (time) from the previous step's action.
        - name: Echo the script's run time
          run: echo 'The time was ${{ steps.run_script.outputs.time }}.'
   
