name: Track Commits
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sh generateLog.sh
    - uses: actions/upload-artifact@v2
      with:
        name: log_artifact
        path: ./commitLog.log
